/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Usuario;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;


/**
 *
 * @author lubuntu
 */
public class Cad_Aluno_1 extends javax.swing.JFrame {

    /**
     * Creates new form Cad_Usuario
     */

    public Cad_Aluno_1() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWrapper = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldRG = new javax.swing.JTextField();
        jTextFieldCPF = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        //jSpinnerNumero.setForeground(new Color(91,95,99));
        jSpinnerNumero = new javax.swing.JSpinner();
        jButtonAvancar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldCel = new javax.swing.JTextField();
        jTextFieldDDDCel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldData_Nasc = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuCad_Aluno = new javax.swing.JMenuItem();
        jMenuCons_Aluno = new javax.swing.JMenuItem();
        jMenuCons_Aluno1 = new javax.swing.JMenuItem();
        jMenuAlt_Aluno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuCad_Professor = new javax.swing.JMenuItem();
        jMenuCons_Professor1 = new javax.swing.JMenuItem();
        jMenuCons_Endereco_Prof = new javax.swing.JMenuItem();
        jMenuAlt_Professor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuCad_Exercicio = new javax.swing.JMenuItem();
        jMenuCons_Exercicio = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuMontar_Treino = new javax.swing.JMenuItem();
        jMenuItemCons_Alt_Exc_Treino = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuItemLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GymManager - Cadastro Aluno");
        setResizable(false);

        jPanelWrapper.setBackground(new java.awt.Color(255, 255, 255));

        jPanelHeader.setBackground(new java.awt.Color(2, 1, 24));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Aluno");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel3.setText("RG:");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel4.setText("CPF:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel6.setText("Celular:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel11.setText("Email:");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel14.setText("Sexo:");

        jTextFieldNome.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldNome.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });

        jTextFieldRG.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldRG.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldRG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRGFocusLost(evt);
            }
        });

        jTextFieldCPF.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldCPF.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCPFFocusLost(evt);
            }
        });

        jComboBoxSexo.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxSexo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jComboBoxSexo.setForeground(new java.awt.Color(91, 95, 99));
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não Binário" }));
        jComboBoxSexo.setPreferredSize(null);

        jTextFieldEmail.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 20))); // NOI18N
        jPanel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel10.setText("Rua:");

        jTextFieldRua.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldRua.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldRuaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldRuaFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel9.setText("Número:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel8.setText("Bairro:");

        jTextFieldBairro.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldBairro.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBairroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBairroFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel7.setText("Cidade:");

        jTextFieldCidade.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldCidade.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCidadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCidadeFocusLost(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel12.setText("Estado:");

        jComboBoxEstado.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxEstado.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jComboBoxEstado.setForeground(new java.awt.Color(91, 95, 99));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF" }));
        jComboBoxEstado.setSelectedIndex(23);

        jSpinnerNumero.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jSpinnerNumero.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9999, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRua)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 165, Short.MAX_VALUE))
                            .addComponent(jTextFieldBairro)))
                    .addComponent(jTextFieldCidade)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jSpinnerNumero))
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEstado)
                .addGap(57, 57, 57))
        );

        jButtonAvancar.setBackground(new java.awt.Color(58, 65, 84));
        jButtonAvancar.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jButtonAvancar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAvancar.setText("Avançar");
        jButtonAvancar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAvancar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAvancarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAvancarMouseEntered(evt);
            }
        });
        jButtonAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel13.setText("Data de Nascimento:");

        jTextFieldCel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldCel.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldCel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldCelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCelFocusLost(evt);
            }
        });

        jTextFieldDDDCel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldDDDCel.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldDDDCel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDDDCel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDDDCelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDDDCelFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel5.setText("-");

        jTextFieldData_Nasc.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldData_Nasc.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldData_Nasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldData_Nasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldData_NascFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldData_NascFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContentLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelContentLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addGap(136, 136, 136))
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelContentLayout.createSequentialGroup()
                                    .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jTextFieldData_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                    .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelContentLayout.createSequentialGroup()
                                    .addComponent(jTextFieldDDDCel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel5)
                                    .addGap(4, 4, 4)
                                    .addComponent(jTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelContentLayout.createSequentialGroup()
                                    .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAvancar)))
                .addContainerGap())
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelContentLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelContentLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelContentLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldData_Nasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDDDCel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanelWrapperLayout = new javax.swing.GroupLayout(jPanelWrapper);
        jPanelWrapper.setLayout(jPanelWrapperLayout);
        jPanelWrapperLayout.setHorizontalGroup(
            jPanelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelWrapperLayout.setVerticalGroup(
            jPanelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrapperLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Sistema");

        jMenuItemInicio.setText("Início");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemInicio);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Aluno");

        jMenuCad_Aluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCad_Aluno.setText("Cadastro");
        jMenuCad_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCad_AlunoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCad_Aluno);

        jMenuCons_Aluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCons_Aluno.setText("Consulta Status");
        jMenuCons_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_AlunoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCons_Aluno);

        jMenuCons_Aluno1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCons_Aluno1.setText("Consulta Endereço");
        jMenuCons_Aluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_Aluno1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCons_Aluno1);

        jMenuAlt_Aluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAlt_Aluno.setText("Alterar/Excluir");
        jMenuAlt_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlt_AlunoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAlt_Aluno);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Professor");

        jMenuCad_Professor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCad_Professor.setText("Cadastro");
        jMenuCad_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCad_ProfessorActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCad_Professor);

        jMenuCons_Professor1.setText("Consulta Informações Adicionais");
        jMenuCons_Professor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_Professor1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCons_Professor1);

        jMenuCons_Endereco_Prof.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCons_Endereco_Prof.setText("Consulta Endereço");
        jMenuCons_Endereco_Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_Endereco_ProfActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCons_Endereco_Prof);

        jMenuAlt_Professor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAlt_Professor.setText("Alterar/Excluir");
        jMenuAlt_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlt_ProfessorActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuAlt_Professor);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exercício");

        jMenuCad_Exercicio.setText("Cadastro");
        jMenuCad_Exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCad_ExercicioActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuCad_Exercicio);

        jMenuCons_Exercicio.setText("Consultar/Alterar/Excluir");
        jMenuCons_Exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_ExercicioActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuCons_Exercicio);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Treino");

        jMenuMontar_Treino.setText("Montar Treino");
        jMenuMontar_Treino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMontar_TreinoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuMontar_Treino);

        jMenuItemCons_Alt_Exc_Treino.setText("Consulta/Alterar/Excluir");
        jMenuItemCons_Alt_Exc_Treino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCons_Alt_Exc_TreinoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemCons_Alt_Exc_Treino);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Opções");

        jMenuItemSair.setText("Sair do Sistema");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSair);

        jMenuItemLogOut.setText("Sair do Perfil");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemLogOut);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarActionPerformed
        
        
        boolean vazio = false;
        String errorMessage = null;
        
        ///////////////// VERIFICAÇÕES DE INPUT /////////////////////////////
        if(jTextFieldNome.getText().length() == 0){
            jTextFieldNome.setBorder(new LineBorder(Color.RED));
            if(errorMessage == null){
                errorMessage = "\nO campo 'Nome' deve ser preenchido";
            }else{
                errorMessage += "\nO campo 'Nome' deve ser preenchido";
            }
            vazio = true;
        }
        if(jTextFieldRG.getText().length() == 0){
            jTextFieldRG.setBorder(new LineBorder(Color.RED));
            if(errorMessage == null){
                errorMessage = "\nO campo 'RG' deve ser preenchido";
            }else{
                errorMessage += "\nO campo 'RG' deve ser preenchido";
            }
            vazio = true;
        }
        if(jTextFieldCPF.getText().length() == 0){
            jTextFieldCPF.setBorder(new LineBorder(Color.RED));
            if(errorMessage == null){
                errorMessage = "\nO campo 'CPF' deve ser preenchido";
            }else{
                errorMessage += "\nO campo 'CPF' deve ser preenchido";
            }
            vazio = true;
        }
        if(jTextFieldData_Nasc.getText().length() != 10){
            jTextFieldData_Nasc.setBorder(new LineBorder(Color.RED));
            if(errorMessage == null){
                errorMessage = "\nO campo 'Data de Nascimento' deve ser preenchido \n Exemplo: 01/01/2000";
            }else{
                errorMessage += "\nO campo 'Data de Nascimento' deve ser preenchido \n Exemplo: 01/01/2000";
            }
            vazio = true;
        }
        if(jTextFieldEmail.getText().length() == 0){
            jTextFieldEmail.setBorder(new LineBorder(Color.RED));
            if(errorMessage == null){
                errorMessage = "\nO campo 'Email' deve ser preenchido";
            }else{
                errorMessage += "\nO campo 'Email' deve ser preenchido";
            }
            vazio = true;
        }
        
        String DDD = jTextFieldDDDCel.getText();
        boolean verificador = false;
        try {
            if(jTextFieldDDDCel.getText().length() != 2){
                jTextFieldDDDCel.setBorder(new LineBorder(Color.RED));
                jTextFieldDDDCel.setText(null);
                if(errorMessage == null){
                    errorMessage = "\nO campo 'DD' deve ser preenchido com 2 números";
                }else{
                    errorMessage += "\nO campo 'DD' deve ser preenchido com 2 números";
                }
                vazio = true;
            }else{
                int DDDConvertido = Integer.parseInt(DDD);
                verificador = true;
            }
        } catch (Exception e) {
            if(verificador == false){
                jTextFieldDDDCel.setBorder(new LineBorder(Color.RED));
                jTextFieldDDDCel.setText(null);
                if(errorMessage == null){
                    errorMessage = "\nO campo 'DD' aceita apenas números";
                }else{
                    errorMessage += "\nO campo 'DD' aceita apenas números";
                }
            }
            vazio = true;
        }        
        
        String Cel = jTextFieldCel.getText();
        boolean verificador2 = false;
        try {
            int CelConvertido = Integer.parseInt(Cel);
            verificador2 = true;
        } catch (Exception ex) {
            if(verificador2 == false){
                jTextFieldCel.setBorder(new LineBorder(Color.RED));
                jTextFieldCel.setText(null);
                if(errorMessage == null){
                    errorMessage = "\nO campo 'Celular' aceita apenas números";
                }else{
                    errorMessage += "\nO campo 'Celular' aceita apenas números";
                }
            }else if(jTextFieldCel.getText().length() != 9){
                    jTextFieldCel.setBorder(new LineBorder(Color.RED));
                    if(errorMessage == null){
                        errorMessage = "\nO campo 'Celular' deve ser preenchido com 9 números";
                    }else{
                        errorMessage += "\nO campo 'Celular' deve ser preenchido com 9 números";
                    }
                }
            vazio = true;
        }

        if(jTextFieldRua.getText().length() == 0){
            jTextFieldRua.setBorder(new LineBorder(Color.RED));
            if(errorMessage == null){
                errorMessage = "\nO campo 'Rua' deve ser preenchido";
            }else{
                errorMessage += "\nO campo 'Rua' deve ser preenchido";
            }
            vazio = true;
        }
        
        if(jTextFieldBairro.getText().length() == 0){
            jTextFieldBairro.setBorder(new LineBorder(Color.RED));
            if(errorMessage == null){
                errorMessage = "\nO campo 'Bairro' deve ser preenchido";
            }else{
                errorMessage += "\nO campo 'Bairro' deve ser preenchido";
            }
            vazio = true;
        }
        
        if(jTextFieldCidade.getText().length() == 0){
            jTextFieldCidade.setBorder(new LineBorder(Color.RED));
            if(errorMessage == null){
                errorMessage = "\nO campo 'Cidade' deve ser preenchido";
            }else{
                errorMessage += "\nO campo 'Cidade' deve ser preenchido";
            }
            vazio = true;
        }
        
        if(errorMessage != null){
            JOptionPane.showMessageDialog(null, errorMessage);
        }
        
        //////////////////////////////////////////////////////////////////////
        if(vazio == false){

            Usuario usuario = new Usuario();
            
            try{
                usuario.setNome(jTextFieldNome.getText());
                usuario.setRg(jTextFieldRG.getText());
                usuario.setCpf(jTextFieldCPF.getText());
                
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                usuario.setData_nasc(formato.parse(jTextFieldData_Nasc.getText()));

                usuario.setSexo(jComboBoxSexo.getSelectedItem().toString());
                usuario.setEmail(jTextFieldEmail.getText());
                usuario.setCelular("("+jTextFieldDDDCel.getText()+") "+ jTextFieldCel.getText());
                usuario.setRua(jTextFieldRua.getText());
                usuario.setNum_casa(Integer.parseInt(jSpinnerNumero.getValue().toString()));
                usuario.setBairro(jTextFieldBairro.getText());
                usuario.setCidade(jTextFieldCidade.getText());
                usuario.setEstado(jComboBoxEstado.getSelectedItem().toString());
                
                Cad_Aluno_2 cad = new Cad_Aluno_2();
                cad.receber_1(usuario);
                dispose();
                cad.setVisible(true);

            }catch(Exception ex){
                JOptionPane.showMessageDialog(null,
                 "Erro = "+ex.getMessage(),"Aluno",0);
            }
   
        }
    
        /*else{
            JOptionPane.showMessageDialog(null, "Há campos obrigatórios a serem preenchidos.");
        }*/
        
    }//GEN-LAST:event_jButtonAvancarActionPerformed

    private void jTextFieldNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusGained
        jTextFieldNome.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldNomeFocusGained

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
        jTextFieldNome.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    private void jTextFieldRGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRGFocusGained
         jTextFieldRG.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldRGFocusGained

    private void jTextFieldCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCPFFocusGained
         jTextFieldCPF.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldCPFFocusGained

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
         jTextFieldEmail.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldRuaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRuaFocusGained
         jTextFieldRua.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldRuaFocusGained

    private void jTextFieldBairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroFocusGained
         jTextFieldBairro.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldBairroFocusGained

    private void jTextFieldCidadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCidadeFocusGained
         jTextFieldCidade.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldCidadeFocusGained

    private void jTextFieldRGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRGFocusLost
        jTextFieldRG.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldRGFocusLost

    private void jTextFieldCPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCPFFocusLost
        jTextFieldCPF.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldCPFFocusLost

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        jTextFieldEmail.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jTextFieldRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldRuaFocusLost
        jTextFieldRua.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldRuaFocusLost

    private void jTextFieldBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBairroFocusLost
        jTextFieldBairro.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldBairroFocusLost

    private void jTextFieldCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCidadeFocusLost
        jTextFieldCidade.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldCidadeFocusLost

    private void jButtonAvancarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAvancarMouseEntered
        jButtonAvancar.setForeground(new Color(58,65,84));
        jButtonAvancar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonAvancarMouseEntered

    private void jButtonAvancarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAvancarMouseExited
        jButtonAvancar.setForeground(Color.WHITE);
        jButtonAvancar.setBackground(new Color(2,1,24));
    }//GEN-LAST:event_jButtonAvancarMouseExited

    private void jTextFieldCelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCelFocusGained
        jTextFieldCel.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldCelFocusGained

    private void jTextFieldCelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCelFocusLost
        jTextFieldCel.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldCelFocusLost

    private void jTextFieldDDDCelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDDDCelFocusGained
        jTextFieldDDDCel.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldDDDCelFocusGained

    private void jTextFieldDDDCelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDDDCelFocusLost
        jTextFieldDDDCel.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldDDDCelFocusLost

    private void jTextFieldData_NascFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldData_NascFocusGained
        jTextFieldData_Nasc.setBorder(new LineBorder(new Color(70,130,180), 2));
    }//GEN-LAST:event_jTextFieldData_NascFocusGained

    private void jTextFieldData_NascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldData_NascFocusLost
       jTextFieldData_Nasc.setBorder(new LineBorder(Color.LIGHT_GRAY, 1));
    }//GEN-LAST:event_jTextFieldData_NascFocusLost

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        dispose();
        Tela_Inicio x = new Tela_Inicio();
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    private void jMenuCad_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCad_AlunoActionPerformed
        Cad_Aluno_1 cad = new Cad_Aluno_1();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCad_AlunoActionPerformed

    private void jMenuCons_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_AlunoActionPerformed
        Cons_Status_Aluno c = new Cons_Status_Aluno();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_AlunoActionPerformed

    private void jMenuCons_Aluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_Aluno1ActionPerformed
        Cons_Endereco_Aluno c = new Cons_Endereco_Aluno();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_Aluno1ActionPerformed

    private void jMenuAlt_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlt_AlunoActionPerformed
        Alterar_Excluir_Aluno a = new Alterar_Excluir_Aluno();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAlt_AlunoActionPerformed

    private void jMenuCad_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCad_ProfessorActionPerformed
        Cad_Professor_1 cad = new Cad_Professor_1();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCad_ProfessorActionPerformed

    private void jMenuCons_Professor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_Professor1ActionPerformed
        Cons_InfoAdicionais_Professor c = new Cons_InfoAdicionais_Professor();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_Professor1ActionPerformed

    private void jMenuCons_Endereco_ProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_Endereco_ProfActionPerformed
        Cons_Endereco_Professor c = new Cons_Endereco_Professor();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_Endereco_ProfActionPerformed

    private void jMenuAlt_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlt_ProfessorActionPerformed
        Alterar_Excluir_Professor a = new Alterar_Excluir_Professor();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAlt_ProfessorActionPerformed

    private void jMenuCad_ExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCad_ExercicioActionPerformed
        Cad_Exercicio cad = new Cad_Exercicio();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCad_ExercicioActionPerformed

    private void jMenuCons_ExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_ExercicioActionPerformed
        Consultar_Alterar_Excluir_Exercicios c = new Consultar_Alterar_Excluir_Exercicios();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_ExercicioActionPerformed

    private void jMenuMontar_TreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMontar_TreinoActionPerformed
        Cad_Treino cad = new Cad_Treino();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuMontar_TreinoActionPerformed

    private void jMenuItemCons_Alt_Exc_TreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCons_Alt_Exc_TreinoActionPerformed
        Consultar_Alterar_Excluir_Treino c = new Consultar_Alterar_Excluir_Treino();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCons_Alt_Exc_TreinoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        Object[] botoes = { "Não", "Sim" };
        int resposta = JOptionPane.showOptionDialog(null,
            "Deseja sair do sistema?", // mensagem para o usuário
            "Confirmação", // o título da janela
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
            botoes, botoes[1]);

        if(resposta == 1){
            System.out.println("Saindo do sistema...");
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOutActionPerformed
        Object[] botoes = { "Não", "Sim" };
        int resposta = JOptionPane.showOptionDialog(null,
            "Deseja sair do perfil?", // mensagem para o usuário
            "Confirmação", // o título da janela
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
            botoes, botoes[1]);

        if(resposta == 1){
            System.out.println("Saindo do perfil...");
            dispose();
            Tela_Login x = new Tela_Login();
            x.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Aluno_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvancar;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuAlt_Aluno;
    private javax.swing.JMenuItem jMenuAlt_Professor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCad_Aluno;
    private javax.swing.JMenuItem jMenuCad_Exercicio;
    private javax.swing.JMenuItem jMenuCad_Professor;
    private javax.swing.JMenuItem jMenuCons_Aluno;
    private javax.swing.JMenuItem jMenuCons_Aluno1;
    private javax.swing.JMenuItem jMenuCons_Endereco_Prof;
    private javax.swing.JMenuItem jMenuCons_Exercicio;
    private javax.swing.JMenuItem jMenuCons_Professor1;
    private javax.swing.JMenuItem jMenuItemCons_Alt_Exc_Treino;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuMontar_Treino;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelWrapper;
    private javax.swing.JSpinner jSpinnerNumero;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCel;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldDDDCel;
    private javax.swing.JTextField jTextFieldData_Nasc;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
}
