/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AlunoDAO;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.Aluno;
import model.Usuario;

/**
 *
 * @author lubuntu
 */
public class Cad_Aluno_3 extends javax.swing.JFrame {

    /**
     * Creates new form Cad_Usuario
     */
    public Cad_Aluno_3() {
        initComponents();
    }

    Aluno aluno = new Aluno();
    Usuario usuario = new Usuario();
    
    public void mostrar(){
        jLabelNome.setText(usuario.getNome());
        jLabelRG.setText(usuario.getRg());
        jLabelCPF.setText(usuario.getCpf());
        jLabelSexo.setText(usuario.getSexo());
        jLabelEmail.setText(usuario.getEmail());
        jLabelCelular.setText(usuario.getCelular());
        jLabelRua.setText(usuario.getRua());
        jLabelNumero.setText(Integer.toString(usuario.getNum_casa()));
        jLabelBairro.setText(usuario.getBairro());
        jLabelCidade.setText(usuario.getCidade());
        jLabelEstado.setText(usuario.getEstado());
        jLabelValor_Mensalidade.setText("R$ "+Double.toString(aluno.getValor_mensalidade()));
        jLabelPeso.setText(Double.toString(aluno.getPeso())+" Kg");
        jLabelAltura.setText(Double.toString(aluno.getAltura())+" cm");
        
        Date data_inicio = aluno.getData_inicio();
        Date data_vencimento = aluno.getData_vencimento();
        Date data_nasc = usuario.getData_nasc();
        
        
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String dataNascimentoFormatada = dateFormat.format(data_nasc);
        String dataInicioFormatada = dateFormat.format(data_inicio);
        String dataVencimentoFormatada = dateFormat.format(data_vencimento);
        
        jLabelData_Nasc.setText(dataNascimentoFormatada);
        jLabelData_Inicio.setText(dataInicioFormatada);
        jLabelData_Vencimento.setText(dataVencimentoFormatada);
    }
    
    public void receber_2(Aluno a, Usuario u){
        
        usuario.setNome(u.getNome());
        usuario.setRg(u.getRg());
        usuario.setCpf(u.getCpf());
        //DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        //String dataNascimentoFormatada = dateFormat.format(u.getData_nasc());
        //String dataContratoFormatada = dateFormat.format(user_teacher.getData_contrato());
        usuario.setData_nasc(u.getData_nasc());
        usuario.setSexo(u.getSexo());
        usuario.setEmail(u.getEmail());
        usuario.setCelular(u.getCelular());
        usuario.setRua(u.getRua());
        usuario.setNum_casa(u.getNum_casa());
        usuario.setBairro(u.getBairro());
        usuario.setCidade(u.getCidade());
        usuario.setEstado(u.getEstado());
        aluno.setPeso(a.getPeso());
        aluno.setAltura(a.getAltura());
        aluno.setValor_mensalidade(a.getValor_mensalidade());
        aluno.setData_vencimento(a.getData_vencimento());
        aluno.setData_inicio(a.getData_inicio());
        aluno.setAtivo(true);

        mostrar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWrapper = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jPanelWrapper2 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jPanelInfo_Pessoais = new javax.swing.JPanel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelData_Nasc = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelSexo1 = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jPanelInfo_Adicionais = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelValor_Mensalidade = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelData_Inicio = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabelData_Vencimento = new javax.swing.JLabel();
        jPanelEndereco2 = new javax.swing.JPanel();
        jLabelRua = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelNumero6 = new javax.swing.JLabel();
        jLabelNumero7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuCad_Aluno = new javax.swing.JMenuItem();
        jMenuCons_Aluno = new javax.swing.JMenuItem();
        jMenuCons_Aluno1 = new javax.swing.JMenuItem();
        jMenuAlt_Aluno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuCad_Professor = new javax.swing.JMenuItem();
        jMenuCons_Professor1 = new javax.swing.JMenuItem();
        jMenuCons_Endereco_Prof = new javax.swing.JMenuItem();
        jMenuAlt_Professor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuCad_Exercicio = new javax.swing.JMenuItem();
        jMenuCons_Exercicio = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuMontar_Treino = new javax.swing.JMenuItem();
        jMenuItemCons_Alt_Exc_Treino = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuItemLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GymManager - Cadastro Aluno");
        setPreferredSize(new java.awt.Dimension(1000, 630));
        setResizable(false);

        jPanelWrapper.setBackground(new java.awt.Color(255, 255, 255));
        jPanelWrapper.setPreferredSize(new java.awt.Dimension(1000, 612));

        jPanelHeader.setBackground(new java.awt.Color(2, 1, 24));
        jPanelHeader.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Confirmar Dados");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setMinimumSize(new java.awt.Dimension(760, 512));
        jPanelContent.setPreferredSize(new java.awt.Dimension(904, 506));

        jButtonCadastrar.setBackground(new java.awt.Color(103, 247, 92));
        jButtonCadastrar.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCadastrarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCadastrarMouseEntered(evt);
            }
        });
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonVoltar.setBackground(new java.awt.Color(217, 216, 216));
        jButtonVoltar.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.setPreferredSize(new java.awt.Dimension(126, 34));
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jPanelWrapper2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelWrapper2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabelNome.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(2, 1, 24));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setText("Nome Completo");

        jPanelInfo_Pessoais.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfo_Pessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações Pessoais", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 20))); // NOI18N

        jLabelCPF.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(2, 1, 24));
        jLabelCPF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCPF.setText("652.689.845-90");

        jLabelRG.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelRG.setForeground(new java.awt.Color(2, 1, 24));
        jLabelRG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRG.setText("87.946.891-X");

        jLabelSexo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelSexo.setForeground(new java.awt.Color(2, 1, 24));
        jLabelSexo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelSexo.setText("Masculino");

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setText("RG");

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setText("CPF");

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setText("Data Nascimento");

        jLabelData_Nasc.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelData_Nasc.setForeground(new java.awt.Color(2, 1, 24));
        jLabelData_Nasc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelData_Nasc.setText("2000-11-03");

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel22.setText("Sexo");

        javax.swing.GroupLayout jPanelInfo_PessoaisLayout = new javax.swing.GroupLayout(jPanelInfo_Pessoais);
        jPanelInfo_Pessoais.setLayout(jPanelInfo_PessoaisLayout);
        jPanelInfo_PessoaisLayout.setHorizontalGroup(
            jPanelInfo_PessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfo_PessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfo_PessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelInfo_PessoaisLayout.createSequentialGroup()
                        .addGroup(jPanelInfo_PessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabelData_Nasc))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfo_PessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCPF)
                    .addComponent(jLabel20)
                    .addComponent(jLabelSexo)
                    .addComponent(jLabel22))
                .addContainerGap())
        );
        jPanelInfo_PessoaisLayout.setVerticalGroup(
            jPanelInfo_PessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfo_PessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfo_PessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(2, 2, 2)
                .addGroup(jPanelInfo_PessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRG)
                    .addComponent(jLabelCPF))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfo_PessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfo_PessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData_Nasc)
                    .addComponent(jLabelSexo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelSexo1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabelSexo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSexo1.setText("Contato");

        jLabelEmail.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(2, 1, 24));
        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmail.setText("nomeemail@email.com");

        jLabelCelular.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelCelular.setForeground(new java.awt.Color(2, 1, 24));
        jLabelCelular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCelular.setText("(19) 98675-9463");

        jPanelInfo_Adicionais.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfo_Adicionais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações Adicionais", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 20))); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Valor da Mensalidade:");

        jLabelValor_Mensalidade.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelValor_Mensalidade.setForeground(new java.awt.Color(2, 1, 24));
        jLabelValor_Mensalidade.setText("Valor");

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setText("Peso");

        jLabelPeso.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelPeso.setForeground(new java.awt.Color(2, 1, 24));
        jLabelPeso.setText("Peso:");

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setText("Altura");

        jLabelAltura.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelAltura.setForeground(new java.awt.Color(2, 1, 24));
        jLabelAltura.setText("Altura");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setText("Data de Início:");

        jLabelData_Inicio.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelData_Inicio.setForeground(new java.awt.Color(2, 1, 24));
        jLabelData_Inicio.setText("Início");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setText("Data de Vencimento");

        jLabelData_Vencimento.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabelData_Vencimento.setForeground(new java.awt.Color(2, 1, 24));
        jLabelData_Vencimento.setText("Vencimento");

        javax.swing.GroupLayout jPanelInfo_AdicionaisLayout = new javax.swing.GroupLayout(jPanelInfo_Adicionais);
        jPanelInfo_Adicionais.setLayout(jPanelInfo_AdicionaisLayout);
        jPanelInfo_AdicionaisLayout.setHorizontalGroup(
            jPanelInfo_AdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfo_AdicionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfo_AdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfo_AdicionaisLayout.createSequentialGroup()
                        .addGroup(jPanelInfo_AdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabelValor_Mensalidade)
                            .addComponent(jLabel17)
                            .addComponent(jLabelData_Inicio)
                            .addComponent(jLabel18)
                            .addComponent(jLabelData_Vencimento))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInfo_AdicionaisLayout.createSequentialGroup()
                        .addGroup(jPanelInfo_AdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabelPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addGroup(jPanelInfo_AdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAltura)
                            .addComponent(jLabel16))
                        .addGap(85, 85, 85))))
        );
        jPanelInfo_AdicionaisLayout.setVerticalGroup(
            jPanelInfo_AdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfo_AdicionaisLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelValor_Mensalidade)
                .addGroup(jPanelInfo_AdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInfo_AdicionaisLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelData_Inicio)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelData_Vencimento)
                        .addGap(20, 20, 20))
                    .addGroup(jPanelInfo_AdicionaisLayout.createSequentialGroup()
                        .addGroup(jPanelInfo_AdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelInfo_AdicionaisLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelAltura))
                            .addGroup(jPanelInfo_AdicionaisLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPeso)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanelEndereco2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEndereco2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Endereço", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 20))); // NOI18N

        jLabelRua.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelRua.setText("Rua");

        jLabelNumero.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelNumero.setText("Número");

        jLabelBairro.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelBairro.setText("Bairro");

        jLabelCidade.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelCidade.setText("Cidade");

        jLabelEstado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelEstado.setText("Estado");

        jLabelNumero6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelNumero6.setText(", ");

        jLabelNumero7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelNumero7.setText(" - ");

        javax.swing.GroupLayout jPanelEndereco2Layout = new javax.swing.GroupLayout(jPanelEndereco2);
        jPanelEndereco2.setLayout(jPanelEndereco2Layout);
        jPanelEndereco2Layout.setHorizontalGroup(
            jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBairro)
                    .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                        .addComponent(jLabelCidade)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelNumero7)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                        .addComponent(jLabelRua)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelNumero6)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelNumero)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanelEndereco2Layout.setVerticalGroup(
            jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRua)
                    .addComponent(jLabelNumero6)
                    .addComponent(jLabelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jLabelNumero7)
                    .addComponent(jLabelEstado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelWrapper2Layout = new javax.swing.GroupLayout(jPanelWrapper2);
        jPanelWrapper2.setLayout(jPanelWrapper2Layout);
        jPanelWrapper2Layout.setHorizontalGroup(
            jPanelWrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrapper2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSexo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelWrapper2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanelWrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelInfo_Pessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelInfo_Adicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addContainerGap())
        );
        jPanelWrapper2Layout.setVerticalGroup(
            jPanelWrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrapper2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelWrapper2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelWrapper2Layout.createSequentialGroup()
                        .addComponent(jPanelInfo_Pessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelInfo_Adicionais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSexo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCelular)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelContentLayout.createSequentialGroup()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrar))
                    .addComponent(jPanelWrapper2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addComponent(jPanelWrapper2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelWrapperLayout = new javax.swing.GroupLayout(jPanelWrapper);
        jPanelWrapper.setLayout(jPanelWrapperLayout);
        jPanelWrapperLayout.setHorizontalGroup(
            jPanelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        jPanelWrapperLayout.setVerticalGroup(
            jPanelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrapperLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContent, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Sistema");

        jMenuItemInicio.setText("Início");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemInicio);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Aluno");

        jMenuCad_Aluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCad_Aluno.setText("Cadastro");
        jMenuCad_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCad_AlunoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCad_Aluno);

        jMenuCons_Aluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCons_Aluno.setText("Consulta Status");
        jMenuCons_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_AlunoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCons_Aluno);

        jMenuCons_Aluno1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCons_Aluno1.setText("Consulta Endereço");
        jMenuCons_Aluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_Aluno1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCons_Aluno1);

        jMenuAlt_Aluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAlt_Aluno.setText("Alterar/Excluir");
        jMenuAlt_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlt_AlunoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAlt_Aluno);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Professor");

        jMenuCad_Professor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCad_Professor.setText("Cadastro");
        jMenuCad_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCad_ProfessorActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCad_Professor);

        jMenuCons_Professor1.setText("Consulta Informações Adicionais");
        jMenuCons_Professor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_Professor1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCons_Professor1);

        jMenuCons_Endereco_Prof.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCons_Endereco_Prof.setText("Consulta Endereço");
        jMenuCons_Endereco_Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_Endereco_ProfActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCons_Endereco_Prof);

        jMenuAlt_Professor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAlt_Professor.setText("Alterar/Excluir");
        jMenuAlt_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlt_ProfessorActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuAlt_Professor);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exercício");

        jMenuCad_Exercicio.setText("Cadastro");
        jMenuCad_Exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCad_ExercicioActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuCad_Exercicio);

        jMenuCons_Exercicio.setText("Consultar/Alterar/Excluir");
        jMenuCons_Exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_ExercicioActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuCons_Exercicio);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Treino");

        jMenuMontar_Treino.setText("Montar Treino");
        jMenuMontar_Treino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMontar_TreinoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuMontar_Treino);

        jMenuItemCons_Alt_Exc_Treino.setText("Consulta/Alterar/Excluir");
        jMenuItemCons_Alt_Exc_Treino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCons_Alt_Exc_TreinoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemCons_Alt_Exc_Treino);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Opções");

        jMenuItemSair.setText("Sair do Sistema");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSair);

        jMenuItemLogOut.setText("Sair do Perfil");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemLogOut);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
        Cad_Aluno_1 cad = new Cad_Aluno_1();
        cad.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        jButtonVoltar.setBackground(Color.BLACK);
        jButtonVoltar.setForeground(Color.WHITE);
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        jButtonVoltar.setBackground(Color.WHITE);
        jButtonVoltar.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarMouseEntered
        jButtonCadastrar.setForeground(new Color(58,65,84));
        jButtonCadastrar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonCadastrarMouseEntered

    private void jButtonCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrarMouseExited
        jButtonCadastrar.setForeground(new Color(51,51,51));
        jButtonCadastrar.setBackground(new Color(103,247,92));
    }//GEN-LAST:event_jButtonCadastrarMouseExited

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        try{
            AlunoDAO aDAO = new AlunoDAO();
            aDAO.inserirAluno(aluno, usuario);
            Cad_Aluno_1 cad = new Cad_Aluno_1();
            cad.setVisible(true);
            dispose();
        }catch (Exception exc) {
         JOptionPane.showMessageDialog(null,
                 "Erro = "+exc.getMessage(),"Aluno",0);
        }
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        dispose();
        Tela_Inicio x = new Tela_Inicio();
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    private void jMenuCad_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCad_AlunoActionPerformed
        Cad_Aluno_1 cad = new Cad_Aluno_1();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCad_AlunoActionPerformed

    private void jMenuCons_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_AlunoActionPerformed
        Cons_Status_Aluno c = new Cons_Status_Aluno();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_AlunoActionPerformed

    private void jMenuCons_Aluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_Aluno1ActionPerformed
        Cons_Endereco_Aluno c = new Cons_Endereco_Aluno();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_Aluno1ActionPerformed

    private void jMenuAlt_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlt_AlunoActionPerformed
        Alterar_Excluir_Aluno a = new Alterar_Excluir_Aluno();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAlt_AlunoActionPerformed

    private void jMenuCad_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCad_ProfessorActionPerformed
        Cad_Professor_1 cad = new Cad_Professor_1();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCad_ProfessorActionPerformed

    private void jMenuCons_Professor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_Professor1ActionPerformed
        Cons_InfoAdicionais_Professor c = new Cons_InfoAdicionais_Professor();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_Professor1ActionPerformed

    private void jMenuCons_Endereco_ProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_Endereco_ProfActionPerformed
        Cons_Endereco_Professor c = new Cons_Endereco_Professor();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_Endereco_ProfActionPerformed

    private void jMenuAlt_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlt_ProfessorActionPerformed
        Alterar_Excluir_Professor a = new Alterar_Excluir_Professor();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAlt_ProfessorActionPerformed

    private void jMenuCad_ExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCad_ExercicioActionPerformed
        Cad_Exercicio cad = new Cad_Exercicio();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCad_ExercicioActionPerformed

    private void jMenuCons_ExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_ExercicioActionPerformed
        Consultar_Alterar_Excluir_Exercicios c = new Consultar_Alterar_Excluir_Exercicios();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_ExercicioActionPerformed

    private void jMenuMontar_TreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMontar_TreinoActionPerformed
        Cad_Treino cad = new Cad_Treino();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuMontar_TreinoActionPerformed

    private void jMenuItemCons_Alt_Exc_TreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCons_Alt_Exc_TreinoActionPerformed
        Consultar_Alterar_Excluir_Treino c = new Consultar_Alterar_Excluir_Treino();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCons_Alt_Exc_TreinoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        Object[] botoes = { "Não", "Sim" };
        int resposta = JOptionPane.showOptionDialog(null,
            "Deseja sair do sistema?", // mensagem para o usuário
            "Confirmação", // o título da janela
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
            botoes, botoes[1]);

        if(resposta == 1){
            System.out.println("Saindo do sistema...");
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOutActionPerformed
        Object[] botoes = { "Não", "Sim" };
        int resposta = JOptionPane.showOptionDialog(null,
            "Deseja sair do perfil?", // mensagem para o usuário
            "Confirmação", // o título da janela
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
            botoes, botoes[1]);

        if(resposta == 1){
            System.out.println("Saindo do perfil...");
            dispose();
            Tela_Login x = new Tela_Login();
            x.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Aluno_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelData_Inicio;
    private javax.swing.JLabel jLabelData_Nasc;
    private javax.swing.JLabel jLabelData_Vencimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelNumero6;
    private javax.swing.JLabel jLabelNumero7;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelSexo1;
    private javax.swing.JLabel jLabelValor_Mensalidade;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuAlt_Aluno;
    private javax.swing.JMenuItem jMenuAlt_Professor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCad_Aluno;
    private javax.swing.JMenuItem jMenuCad_Exercicio;
    private javax.swing.JMenuItem jMenuCad_Professor;
    private javax.swing.JMenuItem jMenuCons_Aluno;
    private javax.swing.JMenuItem jMenuCons_Aluno1;
    private javax.swing.JMenuItem jMenuCons_Endereco_Prof;
    private javax.swing.JMenuItem jMenuCons_Exercicio;
    private javax.swing.JMenuItem jMenuCons_Professor1;
    private javax.swing.JMenuItem jMenuItemCons_Alt_Exc_Treino;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuMontar_Treino;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelEndereco2;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelInfo_Adicionais;
    private javax.swing.JPanel jPanelInfo_Pessoais;
    private javax.swing.JPanel jPanelWrapper;
    private javax.swing.JPanel jPanelWrapper2;
    // End of variables declaration//GEN-END:variables
}
