/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Aluno;
import model.Usuario;

/**
 *
 * @author lubuntu
 */
public class Cad_Aluno_2 extends javax.swing.JFrame {

    public Cad_Aluno_2 () {
        initComponents();
    }

    Aluno aluno = new Aluno();
    Usuario usuario = new Usuario();

    public void receber_1(Usuario u){

        usuario.setNome(u.getNome());
        usuario.setRg(u.getRg());
        usuario.setCpf(u.getCpf());
        usuario.setData_nasc(u.getData_nasc());
        usuario.setSexo(u.getSexo());
        usuario.setEmail(u.getEmail());
        usuario.setCelular(u.getCelular());
        usuario.setRua(u.getRua());
        usuario.setNum_casa(u.getNum_casa());
        usuario.setBairro(u.getBairro());
        usuario.setCidade(u.getCidade());
        usuario.setEstado(u.getEstado());

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelWrapper = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jButtonAvancar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldValorMensalidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jTextFieldAltura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldData_Inicio = new javax.swing.JTextField();
        jTextFieldData_Vencimento = new javax.swing.JTextField();
        jButtonVoltar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemInicio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuCad_Aluno = new javax.swing.JMenuItem();
        jMenuCons_Aluno = new javax.swing.JMenuItem();
        jMenuCons_Aluno1 = new javax.swing.JMenuItem();
        jMenuAlt_Aluno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuCad_Professor = new javax.swing.JMenuItem();
        jMenuCons_Professor1 = new javax.swing.JMenuItem();
        jMenuCons_Endereco_Prof = new javax.swing.JMenuItem();
        jMenuAlt_Professor = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuCad_Exercicio = new javax.swing.JMenuItem();
        jMenuCons_Exercicio = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuMontar_Treino = new javax.swing.JMenuItem();
        jMenuItemCons_Alt_Exc_Treino = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuItemLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GymManager - Cadastro Aluno");
        setPreferredSize(new java.awt.Dimension(1000, 630));
        setResizable(false);

        jPanelWrapper.setBackground(new java.awt.Color(255, 255, 255));

        jPanelHeader.setBackground(new java.awt.Color(2, 1, 24));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Aluno");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));

        jButtonAvancar.setBackground(new java.awt.Color(58, 65, 84));
        jButtonAvancar.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jButtonAvancar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAvancar.setText("Avançar");
        jButtonAvancar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAvancar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAvancarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAvancarMouseEntered(evt);
            }
        });
        jButtonAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Informações Adicionais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 20), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel2.setText("Valor da Mensalidade:");

        jTextFieldValorMensalidade.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldValorMensalidade.setForeground(new java.awt.Color(91, 95, 99));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel3.setText("Peso:");

        jTextFieldPeso.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldPeso.setForeground(new java.awt.Color(91, 95, 99));

        jTextFieldAltura.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldAltura.setForeground(new java.awt.Color(91, 95, 99));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel4.setText("Altura:");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel13.setText("Data de Inicio:");

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel15.setText("Data de Vencimento:");

        jTextFieldData_Inicio.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldData_Inicio.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldData_Inicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldData_Vencimento.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTextFieldData_Vencimento.setForeground(new java.awt.Color(91, 95, 99));
        jTextFieldData_Vencimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPeso)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addComponent(jTextFieldValorMensalidade))
                            .addComponent(jTextFieldData_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldData_Vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldValorMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldData_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldData_Vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButtonVoltar.setBackground(new java.awt.Color(217, 216, 216));
        jButtonVoltar.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltar.setPreferredSize(new java.awt.Dimension(126, 34));
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAvancar)
                .addContainerGap())
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelWrapperLayout = new javax.swing.GroupLayout(jPanelWrapper);
        jPanelWrapper.setLayout(jPanelWrapperLayout);
        jPanelWrapperLayout.setHorizontalGroup(
            jPanelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelWrapperLayout.setVerticalGroup(
            jPanelWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWrapperLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Sistema");

        jMenuItemInicio.setText("Início");
        jMenuItemInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInicioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemInicio);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Aluno");

        jMenuCad_Aluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCad_Aluno.setText("Cadastro");
        jMenuCad_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCad_AlunoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCad_Aluno);

        jMenuCons_Aluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCons_Aluno.setText("Consulta Status");
        jMenuCons_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_AlunoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCons_Aluno);

        jMenuCons_Aluno1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCons_Aluno1.setText("Consulta Endereço");
        jMenuCons_Aluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_Aluno1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCons_Aluno1);

        jMenuAlt_Aluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAlt_Aluno.setText("Alterar/Excluir");
        jMenuAlt_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlt_AlunoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuAlt_Aluno);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Professor");

        jMenuCad_Professor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCad_Professor.setText("Cadastro");
        jMenuCad_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCad_ProfessorActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCad_Professor);

        jMenuCons_Professor1.setText("Consulta Informações Adicionais");
        jMenuCons_Professor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_Professor1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCons_Professor1);

        jMenuCons_Endereco_Prof.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCons_Endereco_Prof.setText("Consulta Endereço");
        jMenuCons_Endereco_Prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_Endereco_ProfActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuCons_Endereco_Prof);

        jMenuAlt_Professor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAlt_Professor.setText("Alterar/Excluir");
        jMenuAlt_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlt_ProfessorActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuAlt_Professor);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Exercício");

        jMenuCad_Exercicio.setText("Cadastro");
        jMenuCad_Exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCad_ExercicioActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuCad_Exercicio);

        jMenuCons_Exercicio.setText("Consultar/Alterar/Excluir");
        jMenuCons_Exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCons_ExercicioActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuCons_Exercicio);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Treino");

        jMenuMontar_Treino.setText("Montar Treino");
        jMenuMontar_Treino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMontar_TreinoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuMontar_Treino);

        jMenuItemCons_Alt_Exc_Treino.setText("Consulta/Alterar/Excluir");
        jMenuItemCons_Alt_Exc_Treino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCons_Alt_Exc_TreinoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemCons_Alt_Exc_Treino);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Opções");

        jMenuItemSair.setText("Sair do Sistema");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSair);

        jMenuItemLogOut.setText("Sair do Perfil");
        jMenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogOutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemLogOut);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAvancarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAvancarMouseEntered
        jButtonAvancar.setForeground(new Color(58,65,84));
        jButtonAvancar.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonAvancarMouseEntered

    private void jButtonAvancarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAvancarMouseExited
        jButtonAvancar.setForeground(Color.WHITE);
        jButtonAvancar.setBackground(new Color(58,65,84));
    }//GEN-LAST:event_jButtonAvancarMouseExited

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        jButtonVoltar.setBackground(Color.BLACK);
        jButtonVoltar.setForeground(new Color(217,216,216));
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        jButtonVoltar.setBackground(new Color(217,216,216));
        jButtonVoltar.setForeground(Color.BLACK);
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
        Cad_Aluno_1 cad = new Cad_Aluno_1();
        cad.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarActionPerformed
        
        aluno.setValor_mensalidade(Double.parseDouble(jTextFieldValorMensalidade.getText()));
        aluno.setPeso(Double.parseDouble(jTextFieldPeso.getText()));
        aluno.setAltura(Double.parseDouble(jTextFieldAltura.getText()));
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        try {
            aluno.setData_inicio(formato.parse(jTextFieldData_Inicio.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(Cad_Aluno_2.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            aluno.setData_vencimento(formato.parse(jTextFieldData_Vencimento.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(Cad_Aluno_2.class.getName()).log(Level.SEVERE, null, ex);
        }
  
        Cad_Aluno_3 cad = new Cad_Aluno_3();
        cad.receber_2(aluno, usuario);
        dispose();
        cad.setVisible(true);

        
    }//GEN-LAST:event_jButtonAvancarActionPerformed

    private void jMenuItemInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInicioActionPerformed
        dispose();
        Tela_Inicio x = new Tela_Inicio();
        x.setVisible(true);
    }//GEN-LAST:event_jMenuItemInicioActionPerformed

    private void jMenuCad_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCad_AlunoActionPerformed
        Cad_Aluno_1 cad = new Cad_Aluno_1();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCad_AlunoActionPerformed

    private void jMenuCons_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_AlunoActionPerformed
        Cons_Status_Aluno c = new Cons_Status_Aluno();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_AlunoActionPerformed

    private void jMenuCons_Aluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_Aluno1ActionPerformed
        Cons_Endereco_Aluno c = new Cons_Endereco_Aluno();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_Aluno1ActionPerformed

    private void jMenuAlt_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlt_AlunoActionPerformed
        Alterar_Excluir_Aluno a = new Alterar_Excluir_Aluno();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAlt_AlunoActionPerformed

    private void jMenuCad_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCad_ProfessorActionPerformed
        Cad_Professor_1 cad = new Cad_Professor_1();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCad_ProfessorActionPerformed

    private void jMenuCons_Professor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_Professor1ActionPerformed
        Cons_InfoAdicionais_Professor c = new Cons_InfoAdicionais_Professor();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_Professor1ActionPerformed

    private void jMenuCons_Endereco_ProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_Endereco_ProfActionPerformed
        Cons_Endereco_Professor c = new Cons_Endereco_Professor();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_Endereco_ProfActionPerformed

    private void jMenuAlt_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlt_ProfessorActionPerformed
        Alterar_Excluir_Professor a = new Alterar_Excluir_Professor();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuAlt_ProfessorActionPerformed

    private void jMenuCad_ExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCad_ExercicioActionPerformed
        Cad_Exercicio cad = new Cad_Exercicio();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCad_ExercicioActionPerformed

    private void jMenuCons_ExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCons_ExercicioActionPerformed
        Consultar_Alterar_Excluir_Exercicios c = new Consultar_Alterar_Excluir_Exercicios();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuCons_ExercicioActionPerformed

    private void jMenuMontar_TreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMontar_TreinoActionPerformed
        Cad_Treino cad = new Cad_Treino();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuMontar_TreinoActionPerformed

    private void jMenuItemCons_Alt_Exc_TreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCons_Alt_Exc_TreinoActionPerformed
        Consultar_Alterar_Excluir_Treino c = new Consultar_Alterar_Excluir_Treino();
        c.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemCons_Alt_Exc_TreinoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        Object[] botoes = { "Não", "Sim" };
        int resposta = JOptionPane.showOptionDialog(null,
            "Deseja sair do sistema?", // mensagem para o usuário
            "Confirmação", // o título da janela
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
            botoes, botoes[1]);

        if(resposta == 1){
            System.out.println("Saindo do sistema...");
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogOutActionPerformed
        Object[] botoes = { "Não", "Sim" };
        int resposta = JOptionPane.showOptionDialog(null,
            "Deseja sair do perfil?", // mensagem para o usuário
            "Confirmação", // o título da janela
            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null,
            botoes, botoes[1]);

        if(resposta == 1){
            System.out.println("Saindo do perfil...");
            dispose();
            Tela_Login x = new Tela_Login();
            x.setVisible(true);
        }

    }//GEN-LAST:event_jMenuItemLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Aluno_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Aluno_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvancar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuAlt_Aluno;
    private javax.swing.JMenuItem jMenuAlt_Professor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCad_Aluno;
    private javax.swing.JMenuItem jMenuCad_Exercicio;
    private javax.swing.JMenuItem jMenuCad_Professor;
    private javax.swing.JMenuItem jMenuCons_Aluno;
    private javax.swing.JMenuItem jMenuCons_Aluno1;
    private javax.swing.JMenuItem jMenuCons_Endereco_Prof;
    private javax.swing.JMenuItem jMenuCons_Exercicio;
    private javax.swing.JMenuItem jMenuCons_Professor1;
    private javax.swing.JMenuItem jMenuItemCons_Alt_Exc_Treino;
    private javax.swing.JMenuItem jMenuItemInicio;
    private javax.swing.JMenuItem jMenuItemLogOut;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuMontar_Treino;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelWrapper;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldData_Inicio;
    private javax.swing.JTextField jTextFieldData_Vencimento;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldValorMensalidade;
    // End of variables declaration//GEN-END:variables
}
